# -*- coding: utf-8 -*-
"""UI components for PHD Ultra Remote Control GUI."""

from .canvas import GraphicalMplCanvas
from .dialogs import StepsDialogChildWindow, PortSetupChildWindow, StepGuideChildWindow
from .theme import switch_theme_qdarktheme, apply_dark_theme, apply_light_theme
from .tray import MySysTrayWidget
from .controllers import (
    on_button_clicked,
    init_combox_syrSize,
    update_combox_syrSize,
    clear_previous_limit,
    get_min_max_limit,
    set_max_min_flow_rate,
    force_level_recommendation,
    update_combox_syr_enabled,
    Quick_mode_param_run,
    validate_and_run,
    set_input_mask,
    add_to_list,
    delete_selected_item,
    update_item_numbers,
    update_setups_dict_custom,
    edit_item_parameter,
    print_setups_dict_custom,
    clear_graph_text,
    fast_btn_timer_start,
    fast_btn_timer_stop,
    rwd_btn_timer_start,
    rwd_btn_timer_stop,
    reset_all_config,
)

__all__ = [
    "GraphicalMplCanvas",
    "StepsDialogChildWindow",
    "PortSetupChildWindow",
    "StepGuideChildWindow",
    "switch_theme_qdarktheme",
    "apply_dark_theme",
    "apply_light_theme",
    "MySysTrayWidget",
    "on_button_clicked",
    "init_combox_syrSize",
    "update_combox_syrSize",
    "clear_previous_limit",
    "get_min_max_limit",
    "set_max_min_flow_rate",
    "force_level_recommendation",
    "update_combox_syr_enabled",
    "Quick_mode_param_run",
    "validate_and_run",
    "set_input_mask",
    "add_to_list",
    "delete_selected_item",
    "update_item_numbers",
    "update_setups_dict_custom",
    "edit_item_parameter",
    "print_setups_dict_custom",
    "clear_graph_text",
    "fast_btn_timer_start",
    "fast_btn_timer_stop",
    "rwd_btn_timer_start",
    "rwd_btn_timer_stop",
    "reset_all_config",
]
